CREATE TABLE pedidos (
  ID_PEDIDO INT NOT NULL AUTO_INCREMENT,
  CLIENTE INT NOT NULL,
  DATA DATE NOT NULL,
  TOTAL FLOAT DEFAULT NULL,
  PRIMARY KEY (ID_PEDIDO),
  INDEX idx_PEDIDOS(ID_PEDIDO)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
ROW_FORMAT = DYNAMIC;